# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll", "~> 4.2.0"
gem "webrick", "~> 1.8.1"

group :jekyll_plugins do
  gem "jekyll-remote-theme"
  gem "jekyll-seo-tag"
  gem "jekyll-asciidoc", "~> 3.0.0"
  gem "jekyll-include-cache"
end

# Standard library gems that need to be explicit for Ruby 3.4+
gem "csv"
gem "logger"
gem "base64"
gem "bigdecimal"
gem "rake"